# SPDX-FileCopyrightText: 2020-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: JS Tests
on: pull_request

jobs:
  jest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        npm-version: [9]

    name: node${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up npm ${{ matrix.npm-version }}
        run: npm i -g npm@${{ matrix.npm-version }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
          flags: javascript
          fail_ci_if_error: ${{ !github.event.pull_request.head.repo.fork }}

  summary:
    runs-on: ubuntu-latest
    needs:
      - jest

    if: always()

    name: npm-test-summary

    steps:
      - name: Jest status
        run: if ${{ needs.jest.result != 'success' && needs.jest.result != 'skipped' }}; then exit 1; fi
