name-template: 'v$RESOLVED_VERSION ðŸš€'
tagline-template: 'Release v$RESOLVED_VERSION ðŸš€'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add \` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'
  default: patch

categories:
  - title: 'ðŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ðŸ§° Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: 'ðŸ“š Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: 'â¬†ï¸ Dependencies'
    labels:
      - 'dependencies'
  - title: 'ðŸ”’ Security'
    labels:
      - 'security'

exclude-labels:
  - 'skip-changelog'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  ## Installation

  Download the zip file from the assets below and install it in your Nextcloud instance.

  ## Documentation

  For more information, please refer to the [documentation](https://github.com/pdarleyjr/NextCloud-App/blob/master/README.md).
