version: "3"

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - db:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - nextcloud_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password-file=/run/secrets/mysql_root_password",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    secrets:
      - mysql_root_password
      - mysql_password

  redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server --requirepass ${REDIS_PASSWORD:-nextcloud}
    secrets:
      - redis_password

  nextcloud:
    image: nextcloud:21.0.2
    restart: always
    ports:
      - 127.0.0.1:8080:80 # Only bind to localhost for security
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - nextcloud:/var/www/html
      - workspace:/workspace
      - ./Repos:/workspace/Repos:cached
      - ./Documents:/workspace/Documents:cached
      - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini:ro
      - ./docker/entrypoint-fix-app.sh:/entrypoint-fix-app.sh:ro
      - ./docker/fix-security-issues.sh:/fix-security-issues.sh:ro
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD_FILE=/run/secrets/redis_password
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=512M
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - "NEXTCLOUD_TRUSTED_DOMAINS=localhost nextcloud 127.0.0.1"
      - OVERWRITEPROTOCOL=https
    networks:
      - nextcloud_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`localhost`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
    secrets:
      - mysql_password
      - redis_password
      - nextcloud_admin_user
      - nextcloud_admin_password
    # Run our fix scripts after container initialization
    entrypoint: ["/bin/sh", "-c", "chmod +x /entrypoint-fix-app.sh && chmod +x /fix-security-issues.sh && /entrypoint.sh apache2-foreground & sleep 30 && /entrypoint-fix-app.sh && /fix-security-issues.sh"]

volumes:
  db:
  nextcloud:
  workspace:

networks:
  nextcloud_network:
    driver: bridge

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt
