version: "3.8"

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - db:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - nextcloud_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pnextcloud",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  nextcloud:
    image: nextcloud:29
    restart: always
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - nextcloud:/var/www/html
      - workspace:/workspace
      - ./Repos:/workspace/Repos:cached
      - ./Documents:/workspace/Documents:cached
      - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini:ro
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=512M
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - "NEXTCLOUD_TRUSTED_DOMAINS=localhost nextcloud 127.0.0.1 *.github.dev *.githubpreview.dev *.app.github.dev"
      - OVERWRITEPROTOCOL=https
    networks:
      - nextcloud_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`localhost`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"

volumes:
  db:
  nextcloud:
  workspace:

networks:
  nextcloud_network:
    driver: bridge
