version: '3.7'

services:
  nextcloud:
    image: nextcloud:latest
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
      - workspace:/workspace
      - ./Repos:/workspace/Repos:cached
      - ./Documents:/workspace/Documents:cached
      - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini:ro
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secret
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - "NEXTCLOUD_TRUSTED_DOMAINS=localhost nextcloud 127.0.0.1 *.github.dev *.githubpreview.dev *.app.github.dev"
      - OVERWRITEPROTOCOL=https
    depends_on:
      - db
    networks:
      - nextcloud_network

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - nextcloud_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  nextcloud_data:
  db_data:
  workspace:

networks:
  nextcloud_network:
    driver: bridge
