name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Docker Compose file
        run: docker-compose config

      - name: Create secrets directory and files
        run: |
          mkdir -p secrets
          echo -n "nextcloud" > secrets/mysql_root_password.txt
          echo -n "nextcloud" > secrets/mysql_password.txt
          echo -n "nextcloud" > secrets/redis_password.txt
          echo -n "admin" > secrets/nextcloud_admin_user.txt
          echo -n "admin" > secrets/nextcloud_admin_password.txt
          chmod 600 secrets/*.txt

      - name: Verify setup script is executable
        run: chmod +x .devcontainer/setup.sh

      - name: Verify fix-app-symlink script is executable
        run: chmod +x fix-app-symlink.sh

      - name: Verify cleanup script is executable
        run: chmod +x cleanup-repository.sh

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint shell scripts
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          find . -type f -name "*.sh" -exec shellcheck {} \;

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: "**/*.md"
          config: |
            {
              "MD013": false,
              "MD033": false
            }
