name: Docker Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create secrets directory and files
        run: |
          mkdir -p secrets
          echo -n "nextcloud" > secrets/mysql_root_password.txt
          echo -n "nextcloud" > secrets/mysql_password.txt
          echo -n "nextcloud" > secrets/redis_password.txt
          echo -n "admin" > secrets/nextcloud_admin_user.txt
          echo -n "admin" > secrets/nextcloud_admin_password.txt
          chmod 600 secrets/*.txt

      - name: Start Docker containers
        run: |
          docker-compose up -d db redis
          # Wait for database to be ready
          sleep 10

      - name: Check Docker containers
        run: docker-compose ps

      - name: Check database connection
        run: |
          docker-compose exec -T db mysql -u nextcloud -pnextcloud -e "SHOW DATABASES;"

      - name: Check Redis connection
        run: |
          docker-compose exec -T redis redis-cli -a nextcloud ping

      - name: Stop Docker containers
        run: docker-compose down
