name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json, mbstring
        tools: composer:v2

    - name: Check PHP Version
      run: php -v

    - name: Check Installed Extensions
      run: php -m

    - name: Check Composer Version
      run: composer --version

    - name: Validate composer.json
      run: composer validate --no-check-lock

    - name: Clear Composer cache
      run: composer clear-cache

    - name: Update dependencies
      run: composer update --no-interaction --prefer-dist
      env:
        COMPOSER_MEMORY_LIMIT: 2G

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
      env:
        COMPOSER_MEMORY_LIMIT: 2G

    - name: List installed packages
      run: composer show

    - name: Check vendor directory
      run: ls -la vendor
