name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json
        tools: composer:v2

    - name: Check PHP Version
      run: php -v

    - name: Check Composer Version
      run: composer --version

    - name: Validate composer.json
      run: composer validate --no-check-lock
      continue-on-error: true

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
      continue-on-error: true

    - name: List installed packages
      run: composer show
      continue-on-error: true
