name: Security Checks

on:
  push:
    branches: [ master ]
    paths:
      - '**.php'
      - '**.js'
      - '**.sh'
      - '**.ps1'
      - 'docker-compose.yml'
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
      - '**.php'
      - '**.js'
      - '**.sh'
      - '**.ps1'
      - 'docker-compose.yml'
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high

  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, php

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  docker-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  shell-script-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
