name: Super-Linter

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'Documents/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'Documents/**'
  workflow_dispatch:

# Limit concurrency to one workflow per branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Define permissions needed for Super-Linter
permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false  # Only lint new or changed files
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Enable specific linters
          VALIDATE_PHP: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_CSS: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_BASH: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_POWERSHELL: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_HTML: true
          VALIDATE_MARKDOWN: true
          # Disable specific linters that might conflict with project standards
          VALIDATE_PHP_PHPCS: false  # We use php-cs-fixer instead
          # Adjust linter behavior
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          LINTER_RULES_PATH: /
          LOG_LEVEL: NOTICE
          FILTER_REGEX_EXCLUDE: '(vendor/.*|node_modules/.*|.*\.min\.js)'
